apiVersion: v2
name: dev-stack
version: 0.1.0
dependencies:
  - name: postgres
    version: 0.19.7
    repository: "oci://registry-1.docker.io/cloudpirates"
    alias: dev-postgres
  - name: eck-elasticsearch
    version: 0.19.1
    repository: "https://helm.elastic.co"
    alias: dev-eck-elasticsearch
  - name: eck-kibana
    version: 0.19.1
    repository: "https://helm.elastic.co"
    alias: dev-eck-kibana
  - name: eck-logstash
    version: 0.19.1
    repository: "https://helm.elastic.co"
    alias: dev-eck-logstash
  - name: rabbitmq
    version: 0.21.9
    repository: "oci://registry-1.docker.io/cloudpirates"
    alias: dev-rabbitmq
  - name: keycloak
    version: 0.21.12
    repository: "oci://registry-1.docker.io/cloudpirates"
    alias: dev-keycloak
  - name: ort-server
    version: ">=0.0.0"
    repository: "file://../ort-server"
