apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ortserver.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ortserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- with .Values.ui.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ortserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "ortserver.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: ui
    spec:
      serviceAccountName: {{ include "ortserver.fullname" . }}-ui-sa
      volumes:
        {{- with .Values.ui.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "ortserver.imagePullSecret" . | nindent 6 }}
      containers:
        - name: {{ include "ortserver.fullname" . }}-ui
          image: "{{ .Values.containerRegistry }}/ort-server-ui:{{ .Chart.AppVersion }}"
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
          {{- if .Values.ui.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: {{ .Values.ui.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.ui.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.ui.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.ui.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: {{ .Values.ui.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.ui.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.ui.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            {{- with .Values.ui.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: UI_URL
              value: {{ .Values.ui.url }}
            - name: UI_API_URL
              value: {{ .Values.ui.apiUrl }}
            - name: UI_AUTHORITY
              value: {{ .Values.ui.authority }}
            - name: UI_CLIENT_ID
              value: {{ .Values.ui.clientId }}
