name: Static Analysis

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  commit-lint:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
    - name: Check Commit Messages
      uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
      with:
        configFile: .commitlintrc.yml
  helm-docs-validation:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Install helm-docs
      run: |
        go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.14.2
        echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

    - name: Validate ort-server README is up to date
      run: |
        helm-docs --chart-to-generate charts/ort-server --sort-values-order=file
        if ! git diff --exit-code charts/ort-server/README.md; then
          echo "The Helm chart docs are not up-to-date. See README.md for how to update them."
          exit 1
        fi
  helm-lint:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Setup Helm
      uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
    - name: Lint dev-stack Helm Chart
      run: |
        helm dependency update charts/dev-stack
        helm lint charts/dev-stack
    - name: Lint ort-server Helm Chart
      run: helm lint charts/ort-server
  renovate-validation:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Validate Repository Renovate Config
      run: npx -y --package renovate -- renovate-config-validator renovate.json
